= Proyecto pokedex
Lucas Abalos <lukotas100@gmail.com>;
v1, {docdate}. 
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introduccion

El proyecta presenta un conjunto de pagina sobre una pokedex funcional en donde  el
usuario navegara en la pagina en donde puede obtener los datos de los pokemons que el quiera ya sea por tipo, generacion o nombre

- El menu de inicio contiene los siguientes archivos:

* `index.html`
* `inicio-mobile.css`
* `inicio-desktop.css`
* `inicio-tablet.css`
* `inicio.js`
* `libreria ScrollReveal.js`

- La pokedex cuenta con los siguientes archivos:

* `pokedex.html`
* `mobileVersion.css`
* `desktopVersion.css`
* `tabletVersion.css`
* `modalStats.css`
* `main.js`
* `obtainForApi.js`
* `modalStatsConfig.js`
* `libreria ScrollReveal.js`

- El formulario de contacto cuenta con los siguientes archivos:

* `pokedex.html`
* `mobileVersion.css`
* `desktopVersion.css`
* `contact-tablet-Desktop.css`
* `contact-mobile.css`
* `contact.js`
* `libreria ScrollReveal.js`
* `libreria EmailJS.js`

El sistema cuenta con 3 paginas las cuales se dividen las siguientes funcionalidades

La primera es el home, el usuario navegara en una pagina de inicio en donde desde ahi podra
hacer una busqueda rapida o ir directamente a la pokedex o al formulario de contacto.

En la seccion de la pokedex el usuario puede realizar la busqueda de cualquiera de los 1025 pokemons existentes y obtener sus datos mas relevantes.

Luego esta la pagina de contacto en donde el usuario puede rellenar un formulario para contactarse con el programador via mail

== Implementación

=== Menu home

==== index.html

El `index.html` vendria a ser la pagina principal del sistema, en esta el usuario podra navegar por diferentes secciones.
La primera seccion es un header, desde ahi el usuario podra ingresar tanto a la pagina de la pokedex como a la de contacto.
La segunda seccion en una pequeña descripcion en donde explica un poco sobre la pokedex y el universo pokemon, en dicha seccion hay otros 2 botones que te llevan a la pokedex o al contacto.
La tercera seccion cuenta con un buscardor rapido de pokemons, en donde el usuario debera de ingresar el nombre de un pokemon valido para que luego le muestre datos basicos.
La cuarta seccion cuenta con la generacion de un pokemon random y unos datos basicos.
Por ultimo cuenta con un footer en donde tambien nos muestran unos datos basicos como en el header.

==== inicio-mobile.css

`inicio-mobile.css` se encarga de estilizar toda la parte mobile de  el html mencionado anteriormente.

==== `inicio-tablet.css`

`inicio-tablet.css` se encarga de estilizar toda la parte para tablets para que se pueda adaptar la pagina a esos dispositivos.

==== `inicio-desktop.css`

`inicio-desktop.css` se encarga de estilizar la pagina para adaptarla a pc.

==== `ScrollReveal.js`

`ScrollReveal.js` Es una libreria de javascript que se encarga de dar animaciones cuando una seccion entra en el viewport.

==== `inicio.js`

`inicio.js` es el archivo javascript que se encarga de manejar toda la logica de la pagina.
A continuacion paso a dar explicacion de todas las funciones

- Variables: Primero declaramos un par de variables, esta seran las siguientes 

* modal = Obtenemos el modal en donde estara ubicado el menu lateral en la version mobile
* menuLateral = Obtenemos el menu lateral que se desplegara en la version mobile 
* btnOpenMenu = Obtenemos el boton que dara paso a abrir tanto el modal, como el menu lateral 
* btnCloseMenu = Obtenemos el boton para cerrar el menu lateral y el modal
* container = Obtenemos el contenedor en donde se va a insertar el pokemon random
* searchButton = Obtenemos el boton de busqueda del input de la busqueda rapida

-toggleMenu() = Esta funcion se encarga de mostrar u ocultar el modal y menu lateral, dependiendo el estado este agrega o quita claaes al modal y menu lateral, 
por ultimo tambien oculta el scroll cuando dicho modal este abierto

- initializeAnimations() = Esta funcion se encarga de inicializar las animaciones que se hacen con la libreria ScrollReveal, dichas animaciones se aplican para
el header, para la informacion principal que se muestra a la hora de mostrar la pagina, para el contenedor de la busqueda rapida y 
tambien para el contenedor del pokemon random

- generateRandomNumber() = Se utiliza para generar un numero del 1 al 1025

- generatePokemon(numberRandom int) = Es una funcion asincronica que recibe un numero random que viene a ser la id del pokemon y este genera su tarjeta de informacion basica, dicha tarjeta se dibuja dentro del container

- document.querySelector(".return-button").addEventListener("click", ()=> {}) = Este evento lo que hace es que al tocar el boton con la flecha para arriba este te manda para el header con una animacion suave

- searchButton.addEventListener("click", () => {}) = Este evento se activa al tocar el boton de busqueda rapida, lo que hace es obtener el input y luego pasarselo como parametro a `generatePokemon()` para que este dibuje el pokemon
que se le paso para que luego se realice un scroll suave hacia abajo mostrando el pokemon buscado pero con un timeout de 100mls por que si no, no se activa

- btnOpenMenu.addEventListener("click", toggleMenu) y btnCloseMenu.addEventListener("click", toggleMenu) = Inicializa los eventos para mostrar y ocultar el modal con los botones btnOpenMenu y btnCloseMenu

- document.addEventListener("DOMContentLoaded", initializeAnimations) = Luego que se cargue el DOOM, se ejecuta la funcion initializeAnimations

- document.addEventListener("DOMContentLoaded", generatePokemon(generateRandomNumber())) = Luego de que se cargue el DOOM, se ejecuta la funcione generatePokemon(generateRandomNumber())